In [7]:
import pandas as pd

df = pd.read_csv('../data/products.csv')

df

,product_id,product_name,category,segment,size,color,price,cogs
0,536,SaigonFlex UC-01,Streetwear,Everyday,S,green,11059.650000,9704.842875
1,537,SaigonFlex UC-02,Streetwear,Everyday,M,silver,9523.076013,5393.870254
2,538,SaigonFlex UC-03,Streetwear,Everyday,L,pink,15951.633158,11371.919278
3,539,SaigonFlex UC-04,Streetwear,Everyday,XL,yellow,15753.717299,8573.172954
4,540,SaigonFlex UC-05,Streetwear,Everyday,S,red,15766.334536,14063.570406
...,...,...,...,...,...,...,...,...
2407,1260,VietMode MP-28,Casual,Activewear,S,red,4603.340000,2553.933032
2408,1261,VietMode MP-29,Casual,Activewear,M,black,5983.876433,4653.660702
2409,1262,VietMode MP-30,Casual,Activewear,L,orange,5983.876433,5684.682611
2410,1263,VietMode MP-31,Casual,Activewear,XL,blue,5984.370000,5685.151500
2411,1264,VietMode MP-32,Casual,Activewear,S,white,5984.370000,3719.884392

In [8]:
df['margin'] = (df['price'] - df['cogs']) / df['price']

df

,product_id,product_name,category,segment,size,color,price,cogs,margin
0,536,SaigonFlex UC-01,Streetwear,Everyday,S,green,11059.650000,9704.842875,0.1225
1,537,SaigonFlex UC-02,Streetwear,Everyday,M,silver,9523.076013,5393.870254,0.4336
2,538,SaigonFlex UC-03,Streetwear,Everyday,L,pink,15951.633158,11371.919278,0.2871
3,539,SaigonFlex UC-04,Streetwear,Everyday,XL,yellow,15753.717299,8573.172954,0.4558
4,540,SaigonFlex UC-05,Streetwear,Everyday,S,red,15766.334536,14063.570406,0.1080
...,...,...,...,...,...,...,...,...,...
2407,1260,VietMode MP-28,Casual,Activewear,S,red,4603.340000,2553.933032,0.4452
2408,1261,VietMode MP-29,Casual,Activewear,M,black,5983.876433,4653.660702,0.2223
2409,1262,VietMode MP-30,Casual,Activewear,L,orange,5983.876433,5684.682611,0.0500
2410,1263,VietMode MP-31,Casual,Activewear,XL,blue,5984.370000,5685.151500,0.0500
2411,1264,VietMode MP-32,Casual,Activewear,S,white,5984.370000,3719.884392,0.3784

In [9]:
res = df.groupby('segment')['margin'].mean()
res.idxmax()

'Standard'