In [16]:
import pandas as pd

customers = pd.read_csv('../data/customers.csv')
orders = pd.read_csv('../data/orders.csv')

customers
# orders

,customer_id,zip,city,signup_date,gender,age_group,acquisition_channel
0,1,15201,Hai Phong,2021-12-30,Female,35-44,social_media
1,2,15201,Hai Phong,2013-12-27,Female,45-54,email_campaign
2,3,15201,Hai Phong,2018-07-24,Female,18-24,organic_search
3,4,15201,Hai Phong,2017-11-29,Male,35-44,referral
4,5,15201,Hai Phong,2022-09-23,Male,55+,organic_search
...,...,...,...,...,...,...,...
121925,157556,59936,Vung Tau,2016-03-03,Female,18-24,direct
121926,157557,59936,Vung Tau,2021-05-11,Female,45-54,social_media
121927,157558,59936,Vung Tau,2017-02-27,Female,25-34,referral
121928,157561,59937,Buon Ma Thuot,2018-10-15,Non-binary,45-54,paid_search
121929,157563,59937,Buon Ma Thuot,2018-08-23,Male,35-44,social_media

In [17]:
df = customers.merge(orders, on='customer_id')
df

,customer_id,zip_x,city,signup_date,gender,age_group,acquisition_channel,order_id,order_date,zip_y,order_status,payment_method,device_type,order_source
0,1,15201,Hai Phong,2021-12-30,Female,35-44,social_media,5280,2012-07-25,15201,delivered,cod,desktop,paid_search
1,1,15201,Hai Phong,2021-12-30,Female,35-44,social_media,184922,2014-05-31,15201,returned,credit_card,mobile,referral
2,1,15201,Hai Phong,2021-12-30,Female,35-44,social_media,308113,2015-07-31,15201,delivered,cod,mobile,paid_search
3,1,15201,Hai Phong,2021-12-30,Female,35-44,social_media,483190,2017-04-23,15201,delivered,cod,mobile,paid_search
4,1,15201,Hai Phong,2021-12-30,Female,35-44,social_media,702081,2020-02-24,15201,delivered,credit_card,mobile,organic_search
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646940,157563,59937,Buon Ma Thuot,2018-08-23,Male,35-44,social_media,709267,2020-04-11,59937,delivered,credit_card,mobile,email_campaign
646941,157563,59937,Buon Ma Thuot,2018-08-23,Male,35-44,social_media,718824,2020-05-29,59937,delivered,credit_card,mobile,social_media
646942,157563,59937,Buon Ma Thuot,2018-08-23,Male,35-44,social_media,721751,2020-06-22,59937,delivered,paypal,tablet,organic_search
646943,157563,59937,Buon Ma Thuot,2018-08-23,Male,35-44,social_media,763157,2021-05-27,59937,delivered,credit_card,mobile,social_media
646944,157563,59937,Buon Ma Thuot,2018-08-23,Male,35-44,social_media,822601,2022-08-31,59937,cancelled,cod,desktop,social_media

In [18]:
df = df[df['age_group'].notna()]

result = df.groupby('age_group').agg(
    total_orders=('order_id', 'count'),
    total_customers=('customer_id', 'nunique')
)

In [19]:
result['avg_orders'] = result['total_orders'] / result['total_customers']
result['avg_orders'].idxmax()

'55+'